# Generated by Django 5.0.2 on 2024-02-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField()),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'riders',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(default=None)),
                ('relationship', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Son', 'Son'), ('Daughter', 'Daugther')], max_length=50)),
                ('percentage', models.FloatField(default=None)),
                ('birthdate', models.DateField()),
                ('type', models.CharField(choices=[('Trustee', 'Trustee'), ('Primary', 'Primary')], max_length=50)),
                ('is_irrevocable', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuapp.client')),
            ],
            options={
                'verbose_name_plural': 'beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_amount', models.FloatField(default=None)),
                ('policy_number', models.CharField(max_length=10)),
                ('number_of_years', models.IntegerField(default=None)),
                ('status', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuapp.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuapp.product')),
                ('riders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuapp.riders')),
            ],
            options={
                'verbose_name_plural': 'insurance plans',
            },
        ),
    ]
