# Generated by Django 5.0.2 on 2024-02-26 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceplan',
            name='riders',
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='rider1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider1', to='manuapp.riders'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='rider2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider2', to='manuapp.riders'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='rider3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider3', to='manuapp.riders'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='rider4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider4', to='manuapp.riders'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='rider5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider5', to='manuapp.riders'),
        ),
    ]
