# Generated by Django 5.0.2 on 2024-02-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuapp', '0003_insuranceplan_rider1_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
