# Generated by Django 5.0.2 on 2024-02-26 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuapp', '0004_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceplan',
            name='number_of_years',
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuapp.client'),
        ),
    ]
